version: '3'

services:
  web:
    build: .
    env_file:
      - .env
    command: sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 config.asgi:application"
    volumes:
      - .:/Dop
      - static_volume:/Dop/staticfiles
      - media_volume:/Dop/mediafiles
    ports:
      - "8019:8000"
    depends_on:
      - dop_db
      - redis
    restart: always

  dop_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: doppi
      POSTGRES_USER: user_doppi
      POSTGRES_PASSWORD: password_doppi
    ports:
      - "5438:5439"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always


  redis:
    image: redis:alpine
    ports:
      - "6374:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis_data:
